language: ruby
rvm:
  - 2.3.0
before_script:
  - "bundle exec rake db:migrate RAILS_ENV=test"
notifications:
  slack: trinity-health-system:vq1qRKvbZpGI09z86I3PBnaf
addons:
  code_climate:
    repo_token: 5f8f95db2e5de911bb31557d9c559bee12f8f900ac068cab0b0266250af006b0